devtools::install_github("dstanley4/learnSampling")
library(learnSampling)
get_cor_samples(rho=.35,n=30,number.of.samples = 1)
my.samples <- get_cor_samples(rho=.35,n=30,number.of.samples=1000)
print(my.samples)
#To view how the sample correlations bounce around a lot
my.samples.sorted <- sort_samples_by_r(my.samples)
print(my.samples.sorted)
#Range of samples
head(my.samples.sorted)
tail(my.samples.sorted)
library(ggplot2)
plot1 <-qplot(r,data=my.samples.sorted,binwidth=.05)
plot1 <- plot1 + coord_cartesian(xlim=c(-.40,.75),ylim=c(0,300))
plot1 <- plot1 + ggtitle("Replications n = 30")
print(plot1)
mean(my.samples.sorted$r)
var(my.samples.sorted$r)
##

my.samples.large <- get_cor_samples(rho = .35,n=75,number.of.samples = 1000)
my.samples.large.sorted <- sort_samples_by_r(my.samples.large)
head(my.samples.large.sorted)
tail(my.samples.large.sorted)
library(ggplot2)
plot2 <- qplot(r,data=my.samples.large.sorted,binwidth=.05)
plot2 <- plot2 + coord_cartesian(xlim=c(-.40,.75),ylim=c(0,300))
plot2 <- plot2 + ggtitle("Replications n = 75")
print(plot2)
mean(my.samples.sorted$r)
##

my.samples.larger <- get_cor_samples(rho=.35,n=150,number.of.samples=1000)
my.samples.larger.sorted <- sort_samples_by_r(my.samples.larger)
head(my.samples.larger.sorted)
tail(my.samples.larger.sorted)
plot3 <- qplot(r,data=my.samples.large.sorted,binwidth=.05)
plot3 <- plot3 + coord_cartesian(xlim=c(-.40,.75),ylim=c(0,300))
plot3 <- plot3 + ggtitle("Replications n = 150")
print(plot3)
mean(my.samples.larger.sorted$r)

library(gridExtra)
grid.arrange(plot1,plot2,plot3,nrow=2)
mean(my.samples$r)
min(my.samples$r)
max(my.samples$r)

mean(my.samples.large$r)
min(my.samples.large$r)
max(my.samples.large$r)

mean(my.samples.larger$r)
min(my.samples.larger$r)
max(my.samples.larger$r)

my.samples.vary <- get_cor_samples(rho=.35,n.min=50,n.max=1000,number.of.samples=1000)
plot4 <- qplot(r,n,data=my.samples.vary)
plot4 <- plot4 + ggtitle("Observed Correlation by Sample Size")
print(plot4)
weighted.mean(my.samples.vary$r,w=my.samples.vary$n)
